{% set name = "caf.distribute" %}
{% set version = "0.7.0" %}
{% set python_min = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_distribute-{{ version }}.tar.gz
  sha256: 8a844eeeb900d1aef16aa987c476d0241c218a8c975fe8359be9b77d2869849b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.2
    - scipy >=1.14
    - pandas >=2
    - tqdm >=4.50.2
    - caf.toolkit >=0.11
    - matplotlib-base >=3.8.2
    - xarray >=2024

test:
  imports:
    - caf.distribute
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Transport-for-the-North/caf.distribute
  summary: Methods to distribute values across arrays
  dev_url: https://github.com/Transport-for-the-North/caf.distribute
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
