{% set name = "caf.distribute" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf_distribute-{{ version }}.tar.gz
  sha256: e257265ac2554957c493d5dc0e1eceacecef47d8a4060255062f13a6bf88247b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >=3.9
    - numpy >=1.22.0,<1.27.0
    - pandas >=1.4.0
    - scipy >=1.10.1
    - tqdm >=4.50.2
    - caf.toolkit >=0.6.0
    - matplotlib-base >=3.8.2

test:
  imports:
    - caf.distribute
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.distribute
  summary: Methods to distribute values across arrays
  dev_url: https://github.com/Transport-for-the-North/caf.distribute
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
